### ISSUE TITLE
IMPROVEMENT: cut down build times

### ISSUE THREAD

**Issue by treinberger** [EdjeElectronics/TensorFlow-Object-Detection-on-the-Raspberry-Pi#27]
IMPROVEMENT:

Depending on which RPi the instructions are being executed on, it's possible to cut down the build time by using

make -j4
make check -j4

instead of

make
make check

On my RPi 3B+, "make check -j4" took only 50 minutes as opposed to 107 minutes as mentioned in the instructions.

HTH

**Comment by EdjeElectronics** [comment]
I have seen weird errors occur when using "make -j4" instead of "make"! I'm paranoid that the OS and build process are not stable enough to handle building protobuf with all four cores. Especially since the "make check" command is already unstable as it is. (I have a hardware engineering background so I'm always paranoid of software 😄)

You can try using the "make -j4" and "make check -j4" commands, but be aware that they might fail.
